[workspace]
members = ["cargo:./apps/brush-app"]

[dist]
cargo-dist-version = "0.30.3"
ci = "github"
installers = []
targets = ["x86_64-pc-windows-msvc"]

[dist.github-action-commits]
"actions/checkout" = "v6"
"actions/upload-artifact" = "v7"
"actions/download-artifact" = "v8"
